//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace RUI.Tasks {
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using Output;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.arl.psu.edu/USMC/ALVTS/ADM")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soa.arl.psu.edu/USMC/ALVTS/ADM", IsNullable=false)]
    public partial class TaskBreakdowns {

        private List<TaskBreakdown> taskBreakdownField;

        [System.Xml.Serialization.XmlElementAttribute("TaskBreakdown")]
        public List<TaskBreakdown> TaskBreakdownField
        {
            get { return taskBreakdownField; }
            set { taskBreakdownField = value; }
        }               
        
        /*
        private TaskBreakdown[] taskBreakdownField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaskBreakdown")]
        public TaskBreakdown[] TaskBreakdown {
            get {
                return this.taskBreakdownField;
            }
            set {
                this.taskBreakdownField = value;
            }
        }
        */
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.arl.psu.edu/USMC/ALVTS/ADM")]
    public partial class TaskBreakdown {
        
        private Task[] taskField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Task")]
        public Task[] Task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.arl.psu.edu/USMC/ALVTS/ADM")]
    public partial class Task {
        
        private Task[] task1Field;
        
        private string nameField;

        private RUIOutput outputStats;

        internal RUIOutput OutputStats
        {
            get { return outputStats; }
            set { outputStats = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Task")]
        public Task[] Task1 {
            get {
                return this.task1Field;
            }
            set {
                this.task1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
